;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="GameplayCue.Unit.Attack",NewTagName="GameplayCue.Unit.BasicAttack")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Type.Basic",DevComment="게임어빌리티 기본공격")
+GameplayTagList=(Tag="Ability.Type.Skill.Ultimate",DevComment="게임 어빌리티 캐릭터 궁극기")
+GameplayTagList=(Tag="Ability.Type.Skill.Weapon",DevComment="게임어빌리티 무기 스킬")
+GameplayTagList=(Tag="Cooldown.Skill",DevComment="스킬 쿨타임 태그")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="쿨타임")
+GameplayTagList=(Tag="Data.Cost.Mana",DevComment="마나 코스트")
+GameplayTagList=(Tag="Data.Damage.Multiplier",DevComment="데미지 계산용 배율")
+GameplayTagList=(Tag="Effect.Attack.Gun",DevComment="총 기본공격")
+GameplayTagList=(Tag="Effect.Hit.Flesh",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Fire",DevComment="원거리발사 태그")
+GameplayTagList=(Tag="Event.Montage.Hit",DevComment="")
+GameplayTagList=(Tag="FX.Character.Army.BasicAttack",DevComment="Army 기본공격효과")
+GameplayTagList=(Tag="FX.Character.Army.Death",DevComment="Army 사망효과")
+GameplayTagList=(Tag="FX.Character.Army.Hit",DevComment="Army 피격효과")
+GameplayTagList=(Tag="FX.Character.Army.Ultimate",DevComment="Army 궁극기효과")
+GameplayTagList=(Tag="FX.Character.Hermit.BasicAttack",DevComment="Hermit 기본공격효과")
+GameplayTagList=(Tag="FX.Character.Hermit.Death",DevComment="Hermit 사망효과")
+GameplayTagList=(Tag="FX.Character.Hermit.Hit",DevComment="Hermit 피격효과")
+GameplayTagList=(Tag="FX.Character.Hermit.Ultimate",DevComment="Hermit 궁극기효과")
+GameplayTagList=(Tag="FX.Character.Hornet.BasicAttack",DevComment="Hornet 기본공격효과")
+GameplayTagList=(Tag="FX.Character.Hornet.Death",DevComment="Hornet 사망효과")
+GameplayTagList=(Tag="FX.Character.Hornet.Hit",DevComment="Hornet 피격효과")
+GameplayTagList=(Tag="FX.Character.Hornet.Ultimate",DevComment="Hornet 궁극기효과")
+GameplayTagList=(Tag="FX.Character.Pioneer.BasicAttack",DevComment="Pioneer 기본공격효과")
+GameplayTagList=(Tag="FX.Character.Pioneer.Death",DevComment="Pioneer 사망효과")
+GameplayTagList=(Tag="FX.Character.Pioneer.Hit",DevComment="Pioneer 피격효과")
+GameplayTagList=(Tag="FX.Character.Pioneer.Ultimate",DevComment="Pioneer 궁극기효과")
+GameplayTagList=(Tag="FX.Character.Tinker.BasicAttack",DevComment="Tinker 기본공격효과")
+GameplayTagList=(Tag="FX.Character.Tinker.Death",DevComment="Tinker 사망효과")
+GameplayTagList=(Tag="FX.Character.Tinker.Hit",DevComment="Tinker 피격효과")
+GameplayTagList=(Tag="FX.Character.Tinker.Ultimate",DevComment="Tinker 궁극기효과")
+GameplayTagList=(Tag="FX.Unit.CherryBee.BasicAttack",DevComment="CherryBee 기본공격 효과")
+GameplayTagList=(Tag="FX.Unit.CherryBee.Death",DevComment="CherryBee 사망효과")
+GameplayTagList=(Tag="FX.Unit.CherryBee.Hit",DevComment="CherryBee 피격효과")
+GameplayTagList=(Tag="FX.Weapon.Blunt.DefaultBlunt.BasicAttack",DevComment="기본망치 기본공격 효과")
+GameplayTagList=(Tag="FX.Weapon.Blunt.DefaultBlunt.Skill",DevComment="기본망치 스킬 효과")
+GameplayTagList=(Tag="FX.Weapon.Book.DefaultBook.BasicAttack",DevComment="기본책 기본공격 효과")
+GameplayTagList=(Tag="FX.Weapon.Book.DefaultBook.Skill",DevComment="기본책 스킬 효과")
+GameplayTagList=(Tag="FX.Weapon.Gun.BlackNose.BasicAttack",DevComment="BlackNose 총 기본공격 효과")
+GameplayTagList=(Tag="FX.Weapon.Gun.BlackNose.Skill",DevComment="BlackNose 총 스킬 효과")
+GameplayTagList=(Tag="FX.Weapon.Staff.DeathMatch.BasicAttack",DevComment="DeathMatch 스태프 기본공격 효과")
+GameplayTagList=(Tag="FX.Weapon.Staff.DeathMatch.Skill",DevComment="DeathMatch 스태프 스킬 효과")
+GameplayTagList=(Tag="FX.Weapon.Sword.Maid.BasicAttack",DevComment="Maid 검 기본공격 효과")
+GameplayTagList=(Tag="FX.Weapon.Sword.Maid.Skill",DevComment="Maid 검 스킬 효과")
+GameplayTagList=(Tag="GameplayCue.Combat.Hit",DevComment="Hit 이펙트 태그")
+GameplayTagList=(Tag="GameplayCue.Unit.BasicAttack",DevComment="기본공격(평타)")
+GameplayTagList=(Tag="GameplayCue.Unit.Death",DevComment="유닛 사망")
+GameplayTagList=(Tag="GameplayCue.Unit.Hit",DevComment="유닛 히트 큐")
+GameplayTagList=(Tag="GameplayCue.Unit.Skill",DevComment="유닛 스킬")
+GameplayTagList=(Tag="GameplayCue.Unit.Ultimate",DevComment="캐릭터 궁극기")
+GameplayTagList=(Tag="Item.Type",DevComment="아이템 타입(대분류)")
+GameplayTagList=(Tag="Item.Type.Armor.Armor",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Hat",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Necklace",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Ring",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Melee",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Melee.Blunt",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Range",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Range.Book",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Range.Gun",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapon.Range.Staff",DevComment="")
+GameplayTagList=(Tag="SetBonus.Stat.AttackPower",DevComment="세트효과 : 공격력")
+GameplayTagList=(Tag="SetBonus.Stat.AttackSpeed",DevComment="세트효과 : 공격속도")
+GameplayTagList=(Tag="SetBonus.Stat.CritRate",DevComment="세트효과 : 치명타 확률")
+GameplayTagList=(Tag="SetBonus.Stat.Defense",DevComment="세트효과 : 방어력")
+GameplayTagList=(Tag="SetBonus.Stat.MaxHP",DevComment="세트효과 : 최대 체력")
+GameplayTagList=(Tag="SetBonus.Stat.MaxMP",DevComment="세트효과 : 최대 마나")
+GameplayTagList=(Tag="SetBonus.Stat.MoveSpeed",DevComment="세트효과 : 이동속도")
+GameplayTagList=(Tag="Skill",DevComment="유닛 스킬")
+GameplayTagList=(Tag="Unit.Attack.Melee",DevComment="근거리 유닛")
+GameplayTagList=(Tag="Unit.Attack.Range",DevComment="원거리 유닛")
+GameplayTagList=(Tag="Unit.Faction.Enemy",DevComment="")
+GameplayTagList=(Tag="Unit.Faction.Friendly.Familiar",DevComment="패밀리어")
+GameplayTagList=(Tag="Unit.Faction.Friendly.Player",DevComment="플레이어")
+GameplayTagList=(Tag="Unit.Rank.Boss",DevComment="보스 유닛")
+GameplayTagList=(Tag="Unit.Rank.Elite",DevComment="정예 유닛")
+GameplayTagList=(Tag="Unit.Rank.Normal",DevComment="일반 유닛")
+GameplayTagList=(Tag="Unit.Role.Dealer",DevComment="딜러 역할군")
+GameplayTagList=(Tag="Unit.Role.Support",DevComment="서포터 역할군")
+GameplayTagList=(Tag="Unit.Role.Tanker",DevComment="탱커 역할군")

